// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYjwYFMdhIdw3j_psvawcmEvff1Bh056w',
    appId: '1:685211825389:web:286ec62b914828622308e4',
    messagingSenderId: '685211825389',
    projectId: 'pemrograman-mobile-dc086',
    authDomain: 'pemrograman-mobile-dc086.firebaseapp.com',
    storageBucket: 'pemrograman-mobile-dc086.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAEluUHSznWQcR9M6wiW7uTOOm1P1p820',
    appId: '1:685211825389:android:2a1163a819fbf41d2308e4',
    messagingSenderId: '685211825389',
    projectId: 'pemrograman-mobile-dc086',
    storageBucket: 'pemrograman-mobile-dc086.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8JybEclWe_VDJPIgAVwAEIhTW1zWHJCU',
    appId: '1:685211825389:ios:e19fc194418730cc2308e4',
    messagingSenderId: '685211825389',
    projectId: 'pemrograman-mobile-dc086',
    storageBucket: 'pemrograman-mobile-dc086.firebasestorage.app',
    iosBundleId: 'com.example.uaspemmob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8JybEclWe_VDJPIgAVwAEIhTW1zWHJCU',
    appId: '1:685211825389:ios:e19fc194418730cc2308e4',
    messagingSenderId: '685211825389',
    projectId: 'pemrograman-mobile-dc086',
    storageBucket: 'pemrograman-mobile-dc086.firebasestorage.app',
    iosBundleId: 'com.example.uaspemmob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi9-6lX_xOdMcvSzg8B5jtO4KZ96G-wxM',
    appId: '1:685211825389:web:32844f52faa47de52308e4',
    messagingSenderId: '685211825389',
    projectId: 'pemrograman-mobile-dc086',
    authDomain: 'pemrograman-mobile-dc086.firebaseapp.com',
    storageBucket: 'pemrograman-mobile-dc086.firebasestorage.app',
  );

}